name: tin_flutter_scafflod
description: "Tin 的 Flutter 脚手架模板"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & 体验（全端可用）
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  pull_to_refresh: ^2.0.0
  flutter_smart_dialog: ^4.9.8+7
  cached_network_image: ^3.4.1

  # 状态管理 & 路由
  get:
    git:
      url: "https://gitcode.com/openharmony-sig/fluttertpc_get.git"

  # 本地存储（全端/部分端）
  shared_preferences:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
      ref: "br_shared_preferences-v2.3.2_ohos"
  path_provider: ^2.1.1

  # 加解密（纯 Dart）
  crypto: ^3.0.6
  encrypt: ^5.0.1

  # 按需启用的原生能力（移动/桌面可用，Web 需要移除）
  permission_handler:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_permission_handler.git"
      path: "permission_handler"
      ref: "br_permission_handler_v11.3.1_ohos"
  sqflite:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_sqflite.git"
      path: "sqflite"
  sqflite_common:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_sqflite.git"
      path: "sqflite_common"
  sqflite_common_ffi:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_sqflite.git"
      path: "sqflite_common_ffi"

  # 其他
  url_launcher: ^6.3.1

dependency_overrides:
  win32: ^5.5.1
  sqflite:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_sqflite.git"
      path: "sqflite"
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"
      ref: "br_path_provider-v2.1.4_ohos"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
